### ISSUE TITLE
Problème de compilation

### ISSUE THREAD

**Issue by Alexis-Gauthier** [ma4s-org/veloinfo#15]
92.69 error[E0425]: cannot find function `size_of` in this scope
92.69    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-postgres-0.8.1/src/types/cube.rs:307:33
92.69     |
92.69 307 |     const PACKED_WIDTH: usize = size_of::<u32>();
92.69     |                                 ^^^^^^^ not found in this scope
92.69     |
92.69 help: consider importing one of these items
92.69     |
92.69 1   + use core::mem::size_of;
92.69     |
92.69 1   + use std::mem::size_of;
92.69     |
92.69
97.12 For more information about this error, try `rustc --explain E0425`.
97.14 error: could not compile `sqlx-postgres` (lib) due to 1 previous error
97.22 error: failed to compile `sqlx-cli v0.8.1`, intermediate artifacts can be found at `/tmp/cargo-installNdG2sU`.
97.22 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
------
failed to solve: process "/bin/sh -c cargo install sqlx-cli --no-default-features --features postgres" did not complete successfully: exit code: 101

C:\Users\client\veloinfo>

**Comment by martinhamel** [comment]
Ça devrait marcher maintenant .

Fait 
`git pull` et 
`docker-compose up`

dis-moi si ça marche !
